# COS 322 Fall 2025 - Homework 1
## Prepare Your ML Workzone and Getting Started with Python Data Libraries


In this assignment, we’ll get familiar with a few essential Python libraries used in machine learning, such as NumPy and Pandas. You’ll practice how to import a dataset and use basic Pandas commands to explore and understand the data.

The assumption here is that you have already, if necessary, done a thorough review of the basics of python, as in [this series](https://realpython.com/courses/python-turtle-beginners/).


Due: Sep 15th, 11:59 PM

Kind reminder: Late submissions will incur a 10% deduction per day past the deadline. Please plan accordingly and submit your work on time!

In [15]:
import numpy as np
print(np.__version__)

2.3.3


###  Imports
Let's import 2 data-related packages and 2 data visualization packages we will use throughout this course: numpy and pandas; matplotlib and seaborn.

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

## Numpy
`numpy` is the typical library used to work with arrays.  You can either convert python lists into arrays, or use one of the many libraries which works with arrays, such as `sklearn`

### **Question 1 (10 points)**

Please create a 5×5 NumPy array of random integers between 1 and 100 (*2 points*). Then compute and print the following:
- Mean and standard deviation of each row (*2 points*)
- The maximum and minimum value in the entire array (*2 points*)
- Multiply the array by a scalar (e.g., 2.5) and display the result (*2 points*)

Please add comments and markdown cells to explain your roughly describe your solution ideas (*2 points*).


#Q1 part one
##Please create a 5×5 NumPy array of random integers between 1 and 100 (2 points).
use np.random.randint to create a fixed sized array with random values


In [17]:
# PLEASE START YOUR SOLUTION
import numpy as np
ar = np.random.randint(1, 101, size=(5, 5))
print(ar)


[[ 66  85  46  92  61]
 [ 80  17   6  88  30]
 [ 93  75   8  29  68]
 [100  15  30  91  73]
 [ 45 100  94  81  60]]


#Q1 part 2
##Mean and standard deviation of each row (2 points)
loop through each row and get its standard deviation and mean. python makes this super easy.


In [18]:
for row in ar:
  print(row.mean(), row.std())

70.0 16.625281952496323
44.2 33.46879143321432
54.6 31.296006134968724
61.8 33.582138109417635
76.0 20.69782597279241


#Q1 part 3
##The maximum and minimum value in the entire array (2 points)
this is also super easy. just call .min(), .max() on the array

In [19]:



print(ar.min(), ar.max())


6 100


#Q1 part 4
##Multiply the array by a scalar (e.g., 2.5) and display the result (2 points)
just like coding in julia, I can multiply the entire array using a operand and scalar

In [20]:
sc = ar*2.5
print(sc)

[[165.  212.5 115.  230.  152.5]
 [200.   42.5  15.  220.   75. ]
 [232.5 187.5  20.   72.5 170. ]
 [250.   37.5  75.  227.5 182.5]
 [112.5 250.  235.  202.5 150. ]]


 ## Pandas
 `Pandas` represents data as DataFrames and Series, where Series are vectors of data and DataFrames represent labeled sets of Series.

###**Loading dataset**

In machine learning, there are several common methods for loading data, today let's try two ways: (1) Load Built-in Datasets and (2) Load from Local Files.


1. **Load Built-in Datasets**

We'll use a dataframe provided by a data collection (Iris) in a library called seaborn.

Iris dataset is one of the most commonly used introductions to data science. It involves 4 features, which are all real numbers between 0 and some maximum size.

In [21]:
import seaborn as sns

# Load the Iris dataset from Seaborn's built-in collection
iris = sns.load_dataset('iris')

# Display the dataset
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [22]:
# Check the type of the dataset
type(iris)

pandas.core.frame.DataFrame

The iris variable is a Pandas DataFrame, it has the following columns: 'sepal_length', 'sepal_width', 'petal_length', 'petal_width' and 'species' (categorical target/ target label)

2. **Load data from Local Files**

You also can load datasets from local files using pandas based on file type
- pd.read_csv("file.csv")
- pd.read_excel("file.xlsx")
- pd.read_json("file.json")

### **Question 2 (10 points)**
Now, please follow the steps below to download the Iris dataset, upload it to your project folder, and load it using Pandas.

- Go to this URL to download the CSV file:
🔗 https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv

- Right-click the page and choose “Save As” and Save the file as: iris.csv

- Upload the dataset via Colab's File Panel
  1. Click the folder icon on the left sidebar in Colab,
  2. Click the “Upload” icon and select your file,
  3. It will appear in /content/
  4. Load it as:
```
# Load the dataset
df = pd.read_csv('/content/iris.csv')

# Preview the data
print(df)

# Check the type of the dataset
type(df)

```







#Q2 part one
Copy paste the code you included earlier after saving iris.csv in the notebook

In [26]:
# PLEASE START YOUR SOLUTION
import pandas as pd
# Load the dataset
df = pd.read_csv('iris.csv')

# Preview the data
print(df)

# Check the type of the dataset
type(df)

iris

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Congratulations🎉! You’ve imported the dataset into your workspace, that’s a solid first step for a machine learning project.

Let’s keep going 💪! Now it’s time to use some basic Pandas commands to take a closer look at the data and see what we’re working with.

### **Basic Pandas commands**
Please learn and practice the following pandas commands by running the code, changing inputs, and observing the output.

df.head(n): view the first n rows

df.tail(m): view the last m rows

df.shape: check the shape of the dataset (rows, columns)

df.columns: see column names

df.info(): check data types and non-null counts

df.describe(): summary statistics for numeric columns

df['species'].value_counts(): value counts for a categorical column

df.iloc[row_index, column_index]: select rows and columns by integer position, and the index always starts at 0

df.loc[row_label, column_label]: select rows and columns using their names, not their numerical positions; filter by condition


In [27]:
# Examples that demonstrate how to use .iloc[] (index-based selection) and .loc[] (label-based selection)
# to access rows and columns in a DataFrame


# .iloc[], indexing Starts from 0

# Get the first row
iris.iloc[0]

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object

In [ ]:
# .iloc[n:m] returns a DataFrame of rows from position n to m-1.
# This follows Python-style slicing, where the end index is exclusive.
# Example: df.iloc[2:5] returns rows at positions 2, 3, and 4.

# Get the first 5 ro
iris.iloc[:5]


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
# Get the first column
iris.iloc[:, 0]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
# Get first 3 rows and first 2 columns
df.iloc[0:3, 0:2]

sepal.length  sepal.width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

In [30]:
# Get all rows where species == 'setosa'
iris.loc[iris['species'] == 'setosa']

sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [ ]:
# Get all rows where petal_length > 5 and only select 'petal_length' and 'species'
iris.loc[iris['petal_length'] > 5, ['petal_length', 'species']]

petal_length     species
83            5.1  versicolor
100           6.0   virginica
101           5.1   virginica
102           5.9   virginica
103           5.6   virginica
104           5.8   virginica
105           6.6   virginica
107           6.3   virginica
108           5.8   virginica
109           6.1   virginica
110           5.1   virginica
111           5.3   virginica
112           5.5   virginica
114           5.1   virginica
115           5.3   virginica
116           5.5   virginica
117           6.7   virginica
118           6.9   virginica
120           5.7   virginica
122           6.7   virginica
124           5.7   virginica
125           6.0   virginica
128           5.6   virginica
129           5.8   virginica
130           6.1   virginica
131           6.4   virginica
132           5.6   virginica
133           5.1   virginica
134           5.6   virginica
135           6.1   virginica
136           5.6   virginica
137           5.5   virginica
139           5.4   virginica
140           5.6   virginica
141           5.1   virginica
142           5.1   virginica
143           5.9   virginica
144           5.7   virginica
145           5.2   virginica
147           5.2   virginica
148           5.4   virginica
149           5.1   virginica

### **Question 3 (10 points)**
Write your code based on the iris dataframe:

Display the first 10 rows (*1 point*)

Display the column names (*1 point*)

Use .iloc[] to display rows at position 15 to 23 (*2 points*)

What is the mean and standard deviation of the sepal_length column? (*2 points*)

Filter the dataset to show only rows where petal_length > 5.0. (*2 points*)

Filter to show only sepal_length and species for flowers with sepal_width < 3.0. (*2 points*)


#Q3 part1
##Display the first 10 rows (1 point)
Use .head(10) to fetch the first 10 rows

In [ ]:
# PLEASE START YOUR SOLUTION
df.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

#Q3 part2
##Display the column names (1 point)
display the column names by using df.columns


In [ ]:
df.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

#Q3 part3
##Use .iloc[] to display rows at position 15 to 23 (2 points)

.iloc[] to display rows at position 15 to 23
we can do 15:24 (because of index) and for columns we can use : to display every column

In [ ]:
df.iloc[15:24, :]

sepal.length  sepal.width  petal.length  petal.width variety
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa
21           5.1          3.7           1.5          0.4  Setosa
22           4.6          3.6           1.0          0.2  Setosa
23           5.1          3.3           1.7          0.5  Setosa

#Q3 part4
##What is the mean and standard deviation of the sepal_length column? (2 points)
we can get the mean and stdev of a specific column by using df['column'].mean() and .std()

In [ ]:
print(iris['sepal_length'].mean(),
iris['sepal_length'].std())

5.843333333333334 0.8280661279778629


#Q3 part5
##Filter the dataset to show only rows where petal_length > 5.0. (2 points)
we can recycle the code you wrote earlier using .loc to get the column and print rows where the values exceed a number

In [ ]:
iris.loc[iris['petal_length'] > 5.0]

sepal_length  sepal_width  petal_length  petal_width     species
83            6.0          2.7           5.1          1.6  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
112           6.8          3.0           5.5          2.1   virginica
114           5.8          2.8           5.1          2.4   virginica
115           6.4          3.2           5.3          2.3   virginica
116           6.5          3.0           5.5          1.8   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
120           6.9          3.2           5.7          2.3   virginica
122           7.7          2.8           6.7          2.0   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
128           6.4          2.8           5.6          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
132           6.4          2.8           5.6          2.2   virginica
133           6.3          2.8           5.1          1.5   virginica
134           6.1          2.6           5.6          1.4   virginica
135           7.7          3.0           6.1          2.3   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
142           5.8          2.7           5.1          1.9   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

#Q3 part6
##Filter to show only sepal_length and species for flowers with sepal_width < 3.0. (2 points)

we can get this by recycling the code you wrote earlier. thanks a lot. it saved me making a GPT query (1.5 bottles of water saved, not dissolved!)

In [ ]:
iris.loc[iris['sepal_width'] < 3.0, ['sepal_length', 'species']]

sepal_length     species
8             4.4      setosa
41            4.5      setosa
53            5.5  versicolor
54            6.5  versicolor
55            5.7  versicolor
57            4.9  versicolor
58            6.6  versicolor
59            5.2  versicolor
60            5.0  versicolor
62            6.0  versicolor
63            6.1  versicolor
64            5.6  versicolor
67            5.8  versicolor
68            6.2  versicolor
69            5.6  versicolor
71            6.1  versicolor
72            6.3  versicolor
73            6.1  versicolor
74            6.4  versicolor
76            6.8  versicolor
78            6.0  versicolor
79            5.7  versicolor
80            5.5  versicolor
81            5.5  versicolor
82            5.8  versicolor
83            6.0  versicolor
87            6.3  versicolor
89            5.5  versicolor
90            5.5  versicolor
92            5.8  versicolor
93            5.0  versicolor
94            5.6  versicolor
96            5.7  versicolor
97            6.2  versicolor
98            5.1  versicolor
99            5.7  versicolor
101           5.8   virginica
103           6.3   virginica
106           4.9   virginica
107           7.3   virginica
108           6.7   virginica
111           6.4   virginica
113           5.7   virginica
114           5.8   virginica
118           7.7   virginica
119           6.0   virginica
121           5.6   virginica
122           7.7   virginica
123           6.3   virginica
126           6.2   virginica
128           6.4   virginica
130           7.4   virginica
132           6.4   virginica
133           6.3   virginica
134           6.1   virginica
142           5.8   virginica
146           6.3   virginica